### ISSUE TITLE
[BUG] SteamVR/OpenXR Suggested Bindings not working for ViveTracker Menu button (Naming mismatch)

### ISSUE THREAD

**Issue by PascalOtto** [ValveSoftware/openvr#1827]
For Vive-Controllers there is a mismatch between the input-name in SteamVR and the OpenXR-Specification. The menu button is named "menu" in openXR-Specification, but is named "application_menu" in SteamVr.
When I suggest `XrActionSuggestedBinding(MyAction, FOpenXRPath("/user/hand/left/input/menu/click")` it works fine and steamVRs binding will look like this
```
              {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/ue/in/vive_left_menu_click"
                  }
               },
               "mode" : "button",
               "parameters" : {
                  "force_input" : "click"
               },
               "path" : "/user/hand/left/input/application_menu"
              },
```
so somehow SteamVr seems to reinterpret "menu" as "application_menu" and it is working correct

But when I do the same for vive trackers it will not be translated to the correct path (I am using the pogo pins) ( `XrActionSuggestedBinding(MyAction, FOpenXRPath("/user/vive_tracker_htcx/role/chest/input/menu/click")`):
```
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/trackers/in/chest-menu"
                  }
               },
               "mode" : "button",
               "parameters" : {
                  "force_input" : "click"
               },
               "path" : "/user/chest/input/menu"
            },
```
The binding will not work for tracker, unless you change it manually to "application_menu".

I guess SteamVR developers fixed the problem caused by the naming mismatch for vive controllers by replacing `menu` with `application_menu`, but forgot to do it for Vive tracker!?

I need to get the bindings to work without manual adjustments.

Also see: [Vive Dev Forum](https://forum.htc.com/topic/18667-bug-steamvropenxr-suggested-bindings-not-working-for-vivetracker-menu-button-naming-mismatch/)

**Comment by PascalOtto** [comment]
This is not the only problem with Suggested Bindings in SteamVRs `XR_HTCX_vive_tracker_interaction` implementation (see [Vive Dev Forum](https://forum.htc.com/topic/18667-bug-steamvropenxr-suggested-bindings-not-working-for-vivetracker-menu-button-naming-mismatch/))

**Comment by danwillm** [comment]
This has been addressed on the SteamVR community forums.
https://steamcommunity.com/app/250820/discussions/7/4357871582657923413/

**Comment by VovaDev** [comment]
Same issue for system(power) and trackpad(thumb) Vive Tracker buttons still present in latest SteamVR beta 2.10.1:
- OpenXR "/input/system/click" path doesn`t translate into SteamVR "input/power" binding
- OpenXR "/input/trackpad/click" path doesn`t translate into SteamVR "input/thumb" binding
